version: '3'
services: 
  nginx:
    image: nginx:alpine
    container_name: contenedornginx
    ports:
      - "8090:80"
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      
  mysql:
    image: mysql:8
    container_name: contenedormysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"